config/routes.rb
Eeservice::Application.routes.draw do


  get "admin/login"
  get "admin/logout"
  get "admin/index"


  match "/mains/whyUS/" => "mains#whyUs"
  match "/mains/about/" => "mains#about"
  match "/mains/rate/" => "mains#rate"
  match "/mains/how/" => "mains#how"
  match "/mains/soon/" => "mains#soon"

  resources :mains
  resources :users
  resources :msg

  root :to => "mains#index"


  match "/logs/iAdd/" => "logs#iAdd"
  match "/logs/jsonAdd/" => "logs#jsonAdd"


 # match "/admin/ilogin/:name/:password" => "admin#iLogin"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/msg.rb
class Msg < ActiveRecord::Base
end

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController
  # GET /msgs
  # GET /msgs.xml
  def index
    @msgs = Msg.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @msgs }
    end
  end

  # GET /msgs/1
  # GET /msgs/1.xml
  def show
    @msg = Msg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @msg }
    end
  end

  # GET /msgs/new
  # GET /msgs/new.xml
  def new
    @msg = Msg.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @msg }
    end
  end

  # GET /msgs/1/edit
  def edit
    @msg = Msg.find(params[:id])
  end

  # POST /msgs
  # POST /msgs.xml
  def create
    @msg = Msg.new(params[:msg])

    respond_to do |format|
      if @msg.save
        format.html { redirect_to(@msg, :notice => 'Msg was successfully created.') }
        format.xml  { render :xml => @msg, :status => :created, :location => @msg }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @msg.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /msgs/1
  # PUT /msgs/1.xml
  def update
    @msg = Msg.find(params[:id])

    respond_to do |format|
      if @msg.update_attributes(params[:msg])
        format.html { redirect_to(@msg, :notice => 'Msg was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @msg.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /msgs/1
  # DELETE /msgs/1.xml
  def destroy
    @msg = Msg.find(params[:id])
    @msg.destroy

    respond_to do |format|
      format.html { redirect_to(msgs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/views/msgs/_form.html.erb
<%= form_for(@msg) do |f| %>
  <% if @msg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@msg.errors.count, "error") %> prohibited this msg from being saved:</h2>

      <ul>
      <% @msg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :[msg %><br />
    <%= f.text_field :[msg %>
  </div>
  <div class="field">
    <%= f.label :own %><br />
    <%= f.text_field :own %>
  </div>
  <div class="field">
    <%= f.label :read %><br />
    <%= f.text_field :read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/msgs/edit.html.erb
<h1>Editing msg</h1>

<%= render 'form' %>

<%= link_to 'Show', @msg %> |
<%= link_to 'Back', msgs_path %>

app/views/msgs/index.html.erb
<h1>Listing msgs</h1>

<table>
  <tr>
    <th>[msg</th>
    <th>Own</th>
    <th>Read</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @msgs.each do |msg| %>
  <tr>
    <td><%= msg.msg %></td>
    <td><%= msg.own %></td>
    <td><%= msg.read %></td>
    <td><%= link_to 'Show', msg %></td>
    <td><%= link_to 'Edit', edit_msg_path(msg) %></td>
    <td><%= link_to 'Destroy', msg, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Msg', new_msg_path %>

app/views/msgs/new.html.erb
<h1>New msg</h1>

<%= render 'form' %>

<%= link_to 'Back', msgs_path %>

app/views/msgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>[msg:</b>
  <%= @msg.[msg %>
</p>

<p>
  <b>Own:</b>
  <%= @msg.own %>
</p>

<p>
  <b>Read:</b>
  <%= @msg.read %>
</p>


<%= link_to 'Edit', edit_msg_path(@msg) %> |
<%= link_to 'Back', msgs_path %>