config/routes.rb
Eeservice::Application.routes.draw do


  get "admin/login"
  get "admin/logout"
  get "admin/index"


  match "/mains/whyUS/" => "mains#whyUs"
  match "/mains/about/" => "mains#about"
  match "/mains/rate/" => "mains#rate"
  match "/mains/how/" => "mains#how"
  match "/mains/soon/" => "mains#soon"

  resources :mains
  resources :users
  resources :msg

  root :to => "mains#index"


  match "/logs/iAdd/" => "logs#iAdd"
  match "/logs/jsonAdd/" => "logs#jsonAdd"


 # match "/admin/ilogin/:name/:password" => "admin#iLogin"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  # GET /mains
  # GET /mains.xml
  def index
    @mains = Main.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mains }
    end
  end

  # GET /mains/1
  # GET /mains/1.xml
  def show
    @main = Main.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @main }
    end
  end

  # GET /mains/new
  # GET /mains/new.xml
  def new
    @main = Main.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @main }
    end
  end

  # GET /mains/1/edit
  def edit
    @main = Main.find(params[:id])
  end

  # POST /mains
  # POST /mains.xml
  def create
    @main = Main.new(params[:main])

    respond_to do |format|
      if @main.save
        format.html { redirect_to(@main, :notice => 'Main was successfully created.') }
        format.xml  { render :xml => @main, :status => :created, :location => @main }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @main.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mains/1
  # PUT /mains/1.xml
  def update
    @main = Main.find(params[:id])

    respond_to do |format|
      if @main.update_attributes(params[:main])
        format.html { redirect_to(@main, :notice => 'Main was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @main.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.xml
  def destroy
    @main = Main.find(params[:id])
    @main.destroy

    respond_to do |format|
      format.html { redirect_to(mains_url) }
      format.xml  { head :ok }
    end
  end

  def whyUS

  end

  def rate

  end

  def how

  end

  def about

  end

  def faq

  end

  def soon

  end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/mains/_form.html.erb
<%= form_for(@main) do |f| %>
  <% if @main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
      <% @main.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mains/about.html.erb
<div style="text-align:center;">
    <img src="images/medium ee shot.png" alt="">  </img>
</div>

app/views/mains/edit.html.erb
<h1>Editing main</h1>

<%= render 'form' %>

<%= link_to 'Show', @main %> |
<%= link_to 'Back', mains_path %>

app/views/mains/faq.html.erb
<div style="text-align:center;">
    <img src="images/medium ee shot.png" alt="">  </img>
</div>

app/views/mains/how.html.erb
<div style="text-align:center;">
    <img src="images/medium ee shot.png" alt="">  </img>
</div>

app/views/mains/index.html.erb
<div style="text-align:center;">
    <img src="images/medium ee shot.png" alt="">  </img>
</div>
<h1>News</h1>

Eden Online Gold Service ( Sv.Odin only !)
Testtttttttttttttttttttttttttttttt
Testtttttttttttttttttttttttttttttt
Testtttttttttttttttttttttttttttttt
Testtttttttttttttttttttttttttttttt
Testtttttttttttttttttttttttttttttt
Testtttttttttttttttttttttttttttttt


<br />

app/views/mains/new.html.erb
<h1>New main</h1>

<%= render 'form' %>

<%= link_to 'Back', mains_path %>

app/views/mains/rate.html.erb
<div style="text-align:center;">
    <img src="images/medium ee shot.png" alt="">  </img>
</div>
<div><h1>Sv.Odin</h1></div>
<div style="text-align:center;">
  <h1>True Money Exchange Rate</h1>
    <img src="images/true money rate 03-mar-2012.png" alt="">  </img>
  </br>อัพเดทล่าสุด 03-March-2012
</div>
     <div style="text-align:center;">____________________________________________________________________________</div>
<div style="text-align:center;">
  <h1>Transfer/Cash Exchange Rate</h1>
    <img src="images/transfer rate 03-mar-2012.png" alt="">  </img>
  </br>อัพเดทล่าสุด 03-March-2012
</div>
 <div style="text-align:center;">____________________________________________________________________________</div>
<div><h1>Sv.Loki -Coming Soon-</h1></div>
<div><h1>Sv.Thor -Coming Soon-</h1></div>

app/views/mains/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_main_path(@main) %> |
<%= link_to 'Back', mains_path %>

app/views/mains/soon.html.erb
<div style="text-align:center;">
    <img src="images/medium ee shot.png" alt="">  </img>
</div>
<h1>Coming Soon!</h1>